package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TBackgroundSchedule generated by hbm2java
 */
public class TBackgroundSchedule implements java.io.Serializable {

	private String bsId;
	private TGroup TGroup;
	private String bsName;
	private Integer bsIndex;
	private String bsMode;
	private Set<TBackgroundPlay> TBackgroundPlays = new HashSet<TBackgroundPlay>(
			0);

	public TBackgroundSchedule() {
	}

	public TBackgroundSchedule(String bsId) {
		this.bsId = bsId;
	}

	public TBackgroundSchedule(String bsId, TGroup TGroup, String bsName,
			Integer bsIndex, String bsMode,
			Set<TBackgroundPlay> TBackgroundPlays) {
		this.bsId = bsId;
		this.TGroup = TGroup;
		this.bsName = bsName;
		this.bsIndex = bsIndex;
		this.bsMode = bsMode;
		this.TBackgroundPlays = TBackgroundPlays;
	}

	public String getBsId() {
		return this.bsId;
	}

	public void setBsId(String bsId) {
		this.bsId = bsId;
	}

	public TGroup getTGroup() {
		return this.TGroup;
	}

	public void setTGroup(TGroup TGroup) {
		this.TGroup = TGroup;
	}

	public String getBsName() {
		return this.bsName;
	}

	public void setBsName(String bsName) {
		this.bsName = bsName;
	}

	public Integer getBsIndex() {
		return this.bsIndex;
	}

	public void setBsIndex(Integer bsIndex) {
		this.bsIndex = bsIndex;
	}

	public String getBsMode() {
		return this.bsMode;
	}

	public void setBsMode(String bsMode) {
		this.bsMode = bsMode;
	}

	public Set<TBackgroundPlay> getTBackgroundPlays() {
		return this.TBackgroundPlays;
	}

	public void setTBackgroundPlays(Set<TBackgroundPlay> TBackgroundPlays) {
		this.TBackgroundPlays = TBackgroundPlays;
	}

}
