package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

/**
 * TBackgroundPlay generated by hbm2java
 */
public class TBackgroundPlay implements java.io.Serializable {

	private String bpId;
	private TBackground TBackground;
	private TGroup TGroup;
	private TBackgroundSchedule TBackgroundSchedule;
	private String bpName;
	private Integer bpIndex;
	private Integer bpColumn;
	private Integer bpRow;
	private Integer bpTop;
	private Integer bpLeft;
	private Integer bpBottom;
	private Integer bpRight;
	private Integer bpHeight;
	private Integer bpWidth;
	private String bpDisplay;
	private String bpPosition;
	private String bpOverflow;
	private Integer bpLayer;
	private Integer bpPaddingTop;
	private Integer bpPaddingRight;
	private Integer bpPaddingBottom;
	private Integer bpPaddingLeft;

	public TBackgroundPlay() {
	}

	public TBackgroundPlay(String bpId) {
		this.bpId = bpId;
	}

	public TBackgroundPlay(String bpId, TBackground TBackground, TGroup TGroup,
			TBackgroundSchedule TBackgroundSchedule, String bpName,
			Integer bpIndex, Integer bpColumn, Integer bpRow, Integer bpTop,
			Integer bpLeft, Integer bpBottom, Integer bpRight,
			Integer bpHeight, Integer bpWidth, String bpDisplay,
			String bpPosition, String bpOverflow, Integer bpLayer,
			Integer bpPaddingTop, Integer bpPaddingRight,
			Integer bpPaddingBottom, Integer bpPaddingLeft) {
		this.bpId = bpId;
		this.TBackground = TBackground;
		this.TGroup = TGroup;
		this.TBackgroundSchedule = TBackgroundSchedule;
		this.bpName = bpName;
		this.bpIndex = bpIndex;
		this.bpColumn = bpColumn;
		this.bpRow = bpRow;
		this.bpTop = bpTop;
		this.bpLeft = bpLeft;
		this.bpBottom = bpBottom;
		this.bpRight = bpRight;
		this.bpHeight = bpHeight;
		this.bpWidth = bpWidth;
		this.bpDisplay = bpDisplay;
		this.bpPosition = bpPosition;
		this.bpOverflow = bpOverflow;
		this.bpLayer = bpLayer;
		this.bpPaddingTop = bpPaddingTop;
		this.bpPaddingRight = bpPaddingRight;
		this.bpPaddingBottom = bpPaddingBottom;
		this.bpPaddingLeft = bpPaddingLeft;
	}

	public String getBpId() {
		return this.bpId;
	}

	public void setBpId(String bpId) {
		this.bpId = bpId;
	}

	public TBackground getTBackground() {
		return this.TBackground;
	}

	public void setTBackground(TBackground TBackground) {
		this.TBackground = TBackground;
	}

	public TGroup getTGroup() {
		return this.TGroup;
	}

	public void setTGroup(TGroup TGroup) {
		this.TGroup = TGroup;
	}

	public TBackgroundSchedule getTBackgroundSchedule() {
		return this.TBackgroundSchedule;
	}

	public void setTBackgroundSchedule(TBackgroundSchedule TBackgroundSchedule) {
		this.TBackgroundSchedule = TBackgroundSchedule;
	}

	public String getBpName() {
		return this.bpName;
	}

	public void setBpName(String bpName) {
		this.bpName = bpName;
	}

	public Integer getBpIndex() {
		return this.bpIndex;
	}

	public void setBpIndex(Integer bpIndex) {
		this.bpIndex = bpIndex;
	}

	public Integer getBpColumn() {
		return this.bpColumn;
	}

	public void setBpColumn(Integer bpColumn) {
		this.bpColumn = bpColumn;
	}

	public Integer getBpRow() {
		return this.bpRow;
	}

	public void setBpRow(Integer bpRow) {
		this.bpRow = bpRow;
	}

	public Integer getBpTop() {
		return this.bpTop;
	}

	public void setBpTop(Integer bpTop) {
		this.bpTop = bpTop;
	}

	public Integer getBpLeft() {
		return this.bpLeft;
	}

	public void setBpLeft(Integer bpLeft) {
		this.bpLeft = bpLeft;
	}

	public Integer getBpBottom() {
		return this.bpBottom;
	}

	public void setBpBottom(Integer bpBottom) {
		this.bpBottom = bpBottom;
	}

	public Integer getBpRight() {
		return this.bpRight;
	}

	public void setBpRight(Integer bpRight) {
		this.bpRight = bpRight;
	}

	public Integer getBpHeight() {
		return this.bpHeight;
	}

	public void setBpHeight(Integer bpHeight) {
		this.bpHeight = bpHeight;
	}

	public Integer getBpWidth() {
		return this.bpWidth;
	}

	public void setBpWidth(Integer bpWidth) {
		this.bpWidth = bpWidth;
	}

	public String getBpDisplay() {
		return this.bpDisplay;
	}

	public void setBpDisplay(String bpDisplay) {
		this.bpDisplay = bpDisplay;
	}

	public String getBpPosition() {
		return this.bpPosition;
	}

	public void setBpPosition(String bpPosition) {
		this.bpPosition = bpPosition;
	}

	public String getBpOverflow() {
		return this.bpOverflow;
	}

	public void setBpOverflow(String bpOverflow) {
		this.bpOverflow = bpOverflow;
	}

	public Integer getBpLayer() {
		return this.bpLayer;
	}

	public void setBpLayer(Integer bpLayer) {
		this.bpLayer = bpLayer;
	}

	public Integer getBpPaddingTop() {
		return this.bpPaddingTop;
	}

	public void setBpPaddingTop(Integer bpPaddingTop) {
		this.bpPaddingTop = bpPaddingTop;
	}

	public Integer getBpPaddingRight() {
		return this.bpPaddingRight;
	}

	public void setBpPaddingRight(Integer bpPaddingRight) {
		this.bpPaddingRight = bpPaddingRight;
	}

	public Integer getBpPaddingBottom() {
		return this.bpPaddingBottom;
	}

	public void setBpPaddingBottom(Integer bpPaddingBottom) {
		this.bpPaddingBottom = bpPaddingBottom;
	}

	public Integer getBpPaddingLeft() {
		return this.bpPaddingLeft;
	}

	public void setBpPaddingLeft(Integer bpPaddingLeft) {
		this.bpPaddingLeft = bpPaddingLeft;
	}

}
