package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

/**
 * TCanvas generated by hbm2java
 */
public class TCanvas implements java.io.Serializable {

	private String cvId;
	private TGroup TGroup;
	private String cvName;
	private Integer cvIndex;
	private Integer cvColumns;
	private Integer cvRows;
	private Integer cvTop;
	private Integer cvLeft;
	private Integer cvBottom;
	private Integer cvRight;
	private Integer cvHeight;
	private Integer cvWidth;
	private String cvDisplay;
	private String cvPosition;
	private String cvOverflow;
	private Integer cvLayer;
	private Integer cvPaddingTop;
	private Integer cvPaddingRight;
	private Integer cvPaddingBottom;
	private Integer cvPaddingLeft;

	public TCanvas() {
	}

	public TCanvas(String cvId) {
		this.cvId = cvId;
	}

	public TCanvas(String cvId, TGroup TGroup, String cvName, Integer cvIndex,
			Integer cvColumns, Integer cvRows, Integer cvTop, Integer cvLeft,
			Integer cvBottom, Integer cvRight, Integer cvHeight,
			Integer cvWidth, String cvDisplay, String cvPosition,
			String cvOverflow, Integer cvLayer, Integer cvPaddingTop,
			Integer cvPaddingRight, Integer cvPaddingBottom,
			Integer cvPaddingLeft) {
		this.cvId = cvId;
		this.TGroup = TGroup;
		this.cvName = cvName;
		this.cvIndex = cvIndex;
		this.cvColumns = cvColumns;
		this.cvRows = cvRows;
		this.cvTop = cvTop;
		this.cvLeft = cvLeft;
		this.cvBottom = cvBottom;
		this.cvRight = cvRight;
		this.cvHeight = cvHeight;
		this.cvWidth = cvWidth;
		this.cvDisplay = cvDisplay;
		this.cvPosition = cvPosition;
		this.cvOverflow = cvOverflow;
		this.cvLayer = cvLayer;
		this.cvPaddingTop = cvPaddingTop;
		this.cvPaddingRight = cvPaddingRight;
		this.cvPaddingBottom = cvPaddingBottom;
		this.cvPaddingLeft = cvPaddingLeft;
	}

	public String getCvId() {
		return this.cvId;
	}

	public void setCvId(String cvId) {
		this.cvId = cvId;
	}

	public TGroup getTGroup() {
		return this.TGroup;
	}

	public void setTGroup(TGroup TGroup) {
		this.TGroup = TGroup;
	}

	public String getCvName() {
		return this.cvName;
	}

	public void setCvName(String cvName) {
		this.cvName = cvName;
	}

	public Integer getCvIndex() {
		return this.cvIndex;
	}

	public void setCvIndex(Integer cvIndex) {
		this.cvIndex = cvIndex;
	}

	public Integer getCvColumns() {
		return this.cvColumns;
	}

	public void setCvColumns(Integer cvColumns) {
		this.cvColumns = cvColumns;
	}

	public Integer getCvRows() {
		return this.cvRows;
	}

	public void setCvRows(Integer cvRows) {
		this.cvRows = cvRows;
	}

	public Integer getCvTop() {
		return this.cvTop;
	}

	public void setCvTop(Integer cvTop) {
		this.cvTop = cvTop;
	}

	public Integer getCvLeft() {
		return this.cvLeft;
	}

	public void setCvLeft(Integer cvLeft) {
		this.cvLeft = cvLeft;
	}

	public Integer getCvBottom() {
		return this.cvBottom;
	}

	public void setCvBottom(Integer cvBottom) {
		this.cvBottom = cvBottom;
	}

	public Integer getCvRight() {
		return this.cvRight;
	}

	public void setCvRight(Integer cvRight) {
		this.cvRight = cvRight;
	}

	public Integer getCvHeight() {
		return this.cvHeight;
	}

	public void setCvHeight(Integer cvHeight) {
		this.cvHeight = cvHeight;
	}

	public Integer getCvWidth() {
		return this.cvWidth;
	}

	public void setCvWidth(Integer cvWidth) {
		this.cvWidth = cvWidth;
	}

	public String getCvDisplay() {
		return this.cvDisplay;
	}

	public void setCvDisplay(String cvDisplay) {
		this.cvDisplay = cvDisplay;
	}

	public String getCvPosition() {
		return this.cvPosition;
	}

	public void setCvPosition(String cvPosition) {
		this.cvPosition = cvPosition;
	}

	public String getCvOverflow() {
		return this.cvOverflow;
	}

	public void setCvOverflow(String cvOverflow) {
		this.cvOverflow = cvOverflow;
	}

	public Integer getCvLayer() {
		return this.cvLayer;
	}

	public void setCvLayer(Integer cvLayer) {
		this.cvLayer = cvLayer;
	}

	public Integer getCvPaddingTop() {
		return this.cvPaddingTop;
	}

	public void setCvPaddingTop(Integer cvPaddingTop) {
		this.cvPaddingTop = cvPaddingTop;
	}

	public Integer getCvPaddingRight() {
		return this.cvPaddingRight;
	}

	public void setCvPaddingRight(Integer cvPaddingRight) {
		this.cvPaddingRight = cvPaddingRight;
	}

	public Integer getCvPaddingBottom() {
		return this.cvPaddingBottom;
	}

	public void setCvPaddingBottom(Integer cvPaddingBottom) {
		this.cvPaddingBottom = cvPaddingBottom;
	}

	public Integer getCvPaddingLeft() {
		return this.cvPaddingLeft;
	}

	public void setCvPaddingLeft(Integer cvPaddingLeft) {
		this.cvPaddingLeft = cvPaddingLeft;
	}

}
