package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TController generated by hbm2java
 */
public class TController implements java.io.Serializable {

	private String ctId;
	private TMonitor TMonitor;
	private TSystem TSystem;
	private TDeviceType TDeviceType;
	private String cssId;
	private String ctName;
	private Integer ctStatus;
	private String ctIp;
	private String ctNetwork;
	private String ctMac;
	private Integer ctUdpPort;
	private Integer ctTcpPort;
	private Date ctRegistTime;
	private String ctVersion;
	private Integer ctLimitPlayCount;
	private Integer ctLimitLayerCount;
	private Integer ctLimitDisk;
	private Integer ctLimitMemory;
	private Integer ctLimitCpu;
	private Integer ctLimitNetwork;

	public TController() {
	}

	public TController(String ctId) {
		this.ctId = ctId;
	}

	public TController(String ctId, TMonitor TMonitor, TSystem TSystem,
			TDeviceType TDeviceType, String cssId, String ctName,
			Integer ctStatus, String ctIp, String ctNetwork, String ctMac,
			Integer ctUdpPort, Integer ctTcpPort, Date ctRegistTime,
			String ctVersion, Integer ctLimitPlayCount,
			Integer ctLimitLayerCount, Integer ctLimitDisk,
			Integer ctLimitMemory, Integer ctLimitCpu, Integer ctLimitNetwork) {
		this.ctId = ctId;
		this.TMonitor = TMonitor;
		this.TSystem = TSystem;
		this.TDeviceType = TDeviceType;
		this.cssId = cssId;
		this.ctName = ctName;
		this.ctStatus = ctStatus;
		this.ctIp = ctIp;
		this.ctNetwork = ctNetwork;
		this.ctMac = ctMac;
		this.ctUdpPort = ctUdpPort;
		this.ctTcpPort = ctTcpPort;
		this.ctRegistTime = ctRegistTime;
		this.ctVersion = ctVersion;
		this.ctLimitPlayCount = ctLimitPlayCount;
		this.ctLimitLayerCount = ctLimitLayerCount;
		this.ctLimitDisk = ctLimitDisk;
		this.ctLimitMemory = ctLimitMemory;
		this.ctLimitCpu = ctLimitCpu;
		this.ctLimitNetwork = ctLimitNetwork;
	}

	public String getCtId() {
		return this.ctId;
	}

	public void setCtId(String ctId) {
		this.ctId = ctId;
	}

	public TMonitor getTMonitor() {
		return this.TMonitor;
	}

	public void setTMonitor(TMonitor TMonitor) {
		this.TMonitor = TMonitor;
	}

	public TSystem getTSystem() {
		return this.TSystem;
	}

	public void setTSystem(TSystem TSystem) {
		this.TSystem = TSystem;
	}

	public TDeviceType getTDeviceType() {
		return this.TDeviceType;
	}

	public void setTDeviceType(TDeviceType TDeviceType) {
		this.TDeviceType = TDeviceType;
	}

	public String getCssId() {
		return this.cssId;
	}

	public void setCssId(String cssId) {
		this.cssId = cssId;
	}

	public String getCtName() {
		return this.ctName;
	}

	public void setCtName(String ctName) {
		this.ctName = ctName;
	}

	public Integer getCtStatus() {
		return this.ctStatus;
	}

	public void setCtStatus(Integer ctStatus) {
		this.ctStatus = ctStatus;
	}

	public String getCtIp() {
		return this.ctIp;
	}

	public void setCtIp(String ctIp) {
		this.ctIp = ctIp;
	}

	public String getCtNetwork() {
		return this.ctNetwork;
	}

	public void setCtNetwork(String ctNetwork) {
		this.ctNetwork = ctNetwork;
	}

	public String getCtMac() {
		return this.ctMac;
	}

	public void setCtMac(String ctMac) {
		this.ctMac = ctMac;
	}

	public Integer getCtUdpPort() {
		return this.ctUdpPort;
	}

	public void setCtUdpPort(Integer ctUdpPort) {
		this.ctUdpPort = ctUdpPort;
	}

	public Integer getCtTcpPort() {
		return this.ctTcpPort;
	}

	public void setCtTcpPort(Integer ctTcpPort) {
		this.ctTcpPort = ctTcpPort;
	}

	public Date getCtRegistTime() {
		return this.ctRegistTime;
	}

	public void setCtRegistTime(Date ctRegistTime) {
		this.ctRegistTime = ctRegistTime;
	}

	public String getCtVersion() {
		return this.ctVersion;
	}

	public void setCtVersion(String ctVersion) {
		this.ctVersion = ctVersion;
	}

	public Integer getCtLimitPlayCount() {
		return this.ctLimitPlayCount;
	}

	public void setCtLimitPlayCount(Integer ctLimitPlayCount) {
		this.ctLimitPlayCount = ctLimitPlayCount;
	}

	public Integer getCtLimitLayerCount() {
		return this.ctLimitLayerCount;
	}

	public void setCtLimitLayerCount(Integer ctLimitLayerCount) {
		this.ctLimitLayerCount = ctLimitLayerCount;
	}

	public Integer getCtLimitDisk() {
		return this.ctLimitDisk;
	}

	public void setCtLimitDisk(Integer ctLimitDisk) {
		this.ctLimitDisk = ctLimitDisk;
	}

	public Integer getCtLimitMemory() {
		return this.ctLimitMemory;
	}

	public void setCtLimitMemory(Integer ctLimitMemory) {
		this.ctLimitMemory = ctLimitMemory;
	}

	public Integer getCtLimitCpu() {
		return this.ctLimitCpu;
	}

	public void setCtLimitCpu(Integer ctLimitCpu) {
		this.ctLimitCpu = ctLimitCpu;
	}

	public Integer getCtLimitNetwork() {
		return this.ctLimitNetwork;
	}

	public void setCtLimitNetwork(Integer ctLimitNetwork) {
		this.ctLimitNetwork = ctLimitNetwork;
	}

}
