package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TDeviceType generated by hbm2java
 */
public class TDeviceType implements java.io.Serializable {

	private int dtType;
	private String dtName;
	private String dtComment;
	private Set<TSystem> TSystems = new HashSet<TSystem>(0);
	private Set<TServer> TServers = new HashSet<TServer>(0);
	private Set<TController> TControllers = new HashSet<TController>(0);

	public TDeviceType() {
	}

	public TDeviceType(int dtType) {
		this.dtType = dtType;
	}

	public TDeviceType(int dtType, String dtName, String dtComment,
			Set<TSystem> TSystems, Set<TServer> TServers,
			Set<TController> TControllers) {
		this.dtType = dtType;
		this.dtName = dtName;
		this.dtComment = dtComment;
		this.TSystems = TSystems;
		this.TServers = TServers;
		this.TControllers = TControllers;
	}

	public int getDtType() {
		return this.dtType;
	}

	public void setDtType(int dtType) {
		this.dtType = dtType;
	}

	public String getDtName() {
		return this.dtName;
	}

	public void setDtName(String dtName) {
		this.dtName = dtName;
	}

	public String getDtComment() {
		return this.dtComment;
	}

	public void setDtComment(String dtComment) {
		this.dtComment = dtComment;
	}

	public Set<TSystem> getTSystems() {
		return this.TSystems;
	}

	public void setTSystems(Set<TSystem> TSystems) {
		this.TSystems = TSystems;
	}

	public Set<TServer> getTServers() {
		return this.TServers;
	}

	public void setTServers(Set<TServer> TServers) {
		this.TServers = TServers;
	}

	public Set<TController> getTControllers() {
		return this.TControllers;
	}

	public void setTControllers(Set<TController> TControllers) {
		this.TControllers = TControllers;
	}

}
