package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

/**
 * TFontResource generated by hbm2java
 */
public class TFontResource implements java.io.Serializable {

	private String frId;
	private TServer TServer;
	private String frName;
	private Integer frType;
	private String frAddr;

	public TFontResource() {
	}

	public TFontResource(String frId) {
		this.frId = frId;
	}

	public TFontResource(String frId, TServer TServer, String frName,
			Integer frType, String frAddr) {
		this.frId = frId;
		this.TServer = TServer;
		this.frName = frName;
		this.frType = frType;
		this.frAddr = frAddr;
	}

	public String getFrId() {
		return this.frId;
	}

	public void setFrId(String frId) {
		this.frId = frId;
	}

	public TServer getTServer() {
		return this.TServer;
	}

	public void setTServer(TServer TServer) {
		this.TServer = TServer;
	}

	public String getFrName() {
		return this.frName;
	}

	public void setFrName(String frName) {
		this.frName = frName;
	}

	public Integer getFrType() {
		return this.frType;
	}

	public void setFrType(Integer frType) {
		this.frType = frType;
	}

	public String getFrAddr() {
		return this.frAddr;
	}

	public void setFrAddr(String frAddr) {
		this.frAddr = frAddr;
	}

}
