package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

/**
 * TFontBackground generated by hbm2java
 */
public class TFontBackground implements java.io.Serializable {

	private String fbId;
	private TMonitor TMonitor;
	private Integer fbType;
	private String fbUri;
	private String fbComment;

	public TFontBackground() {
	}

	public TFontBackground(String fbId) {
		this.fbId = fbId;
	}

	public TFontBackground(String fbId, TMonitor TMonitor, Integer fbType,
			String fbUri, String fbComment) {
		this.fbId = fbId;
		this.TMonitor = TMonitor;
		this.fbType = fbType;
		this.fbUri = fbUri;
		this.fbComment = fbComment;
	}

	public String getFbId() {
		return this.fbId;
	}

	public void setFbId(String fbId) {
		this.fbId = fbId;
	}

	public TMonitor getTMonitor() {
		return this.TMonitor;
	}

	public void setTMonitor(TMonitor TMonitor) {
		this.TMonitor = TMonitor;
	}

	public Integer getFbType() {
		return this.fbType;
	}

	public void setFbType(Integer fbType) {
		this.fbType = fbType;
	}

	public String getFbUri() {
		return this.fbUri;
	}

	public void setFbUri(String fbUri) {
		this.fbUri = fbUri;
	}

	public String getFbComment() {
		return this.fbComment;
	}

	public void setFbComment(String fbComment) {
		this.fbComment = fbComment;
	}

}
