package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TGateway generated by hbm2java
 */
public class TGateway implements java.io.Serializable {

	private String gwId;
	private String gwName;
	private Integer gwStatus;
	private String gwIp;
	private String gwNetwork;
	private String gwMac;
	private Integer gwTcpPort;
	private Integer gwUdpPort;
	private Date gwRegistTime;
	private Set<TSystem> TSystems = new HashSet<TSystem>(0);

	public TGateway() {
	}

	public TGateway(String gwId) {
		this.gwId = gwId;
	}

	public TGateway(String gwId, String gwName, Integer gwStatus, String gwIp,
			String gwNetwork, String gwMac, Integer gwTcpPort,
			Integer gwUdpPort, Date gwRegistTime, Set<TSystem> TSystems) {
		this.gwId = gwId;
		this.gwName = gwName;
		this.gwStatus = gwStatus;
		this.gwIp = gwIp;
		this.gwNetwork = gwNetwork;
		this.gwMac = gwMac;
		this.gwTcpPort = gwTcpPort;
		this.gwUdpPort = gwUdpPort;
		this.gwRegistTime = gwRegistTime;
		this.TSystems = TSystems;
	}

	public String getGwId() {
		return this.gwId;
	}

	public void setGwId(String gwId) {
		this.gwId = gwId;
	}

	public String getGwName() {
		return this.gwName;
	}

	public void setGwName(String gwName) {
		this.gwName = gwName;
	}

	public Integer getGwStatus() {
		return this.gwStatus;
	}

	public void setGwStatus(Integer gwStatus) {
		this.gwStatus = gwStatus;
	}

	public String getGwIp() {
		return this.gwIp;
	}

	public void setGwIp(String gwIp) {
		this.gwIp = gwIp;
	}

	public String getGwNetwork() {
		return this.gwNetwork;
	}

	public void setGwNetwork(String gwNetwork) {
		this.gwNetwork = gwNetwork;
	}

	public String getGwMac() {
		return this.gwMac;
	}

	public void setGwMac(String gwMac) {
		this.gwMac = gwMac;
	}

	public Integer getGwTcpPort() {
		return this.gwTcpPort;
	}

	public void setGwTcpPort(Integer gwTcpPort) {
		this.gwTcpPort = gwTcpPort;
	}

	public Integer getGwUdpPort() {
		return this.gwUdpPort;
	}

	public void setGwUdpPort(Integer gwUdpPort) {
		this.gwUdpPort = gwUdpPort;
	}

	public Date getGwRegistTime() {
		return this.gwRegistTime;
	}

	public void setGwRegistTime(Date gwRegistTime) {
		this.gwRegistTime = gwRegistTime;
	}

	public Set<TSystem> getTSystems() {
		return this.TSystems;
	}

	public void setTSystems(Set<TSystem> TSystems) {
		this.TSystems = TSystems;
	}

}
