package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TGroup generated by hbm2java
 */
public class TGroup implements java.io.Serializable {

	private String gpId;
	private TSystem TSystem;
	private String gpName;
	private Integer gpIndex;
	private Integer gpColumns;
	private Integer gpRows;
	private Integer gpUnitHeight;
	private Integer gpUnitWidth;
	private Integer gpTop;
	private Integer gpLeft;
	private Integer gpBottom;
	private Integer gpRight;
	private Integer gpHeight;
	private Integer gpWidth;
	private String gpDisplay;
	private String gpPosition;
	private String gpOverflow;
	private Integer gpLayer;
	private Integer gpPaddingTop;
	private Integer gpPaddingRight;
	private Integer gpPaddingBottom;
	private Integer gpPaddingLeft;
	private Set<TReGroupServer> TReGroupServers = new HashSet<TReGroupServer>(0);
	private Set<TVideoPlay> TVideoPlays = new HashSet<TVideoPlay>(0);
	private Set<TBackgroundSchedule> TBackgroundSchedules = new HashSet<TBackgroundSchedule>(
			0);
	private Set<TBackgroundPlay> TBackgroundPlays = new HashSet<TBackgroundPlay>(
			0);
	private Set<TMonitor> TMonitors = new HashSet<TMonitor>(0);
	private Set<TTemplate> TTemplates = new HashSet<TTemplate>(0);
	private Set<TBackground> TBackgrounds = new HashSet<TBackground>(0);
	private Set<TVideoSchedule> TVideoSchedules = new HashSet<TVideoSchedule>(0);
	private Set<TReGroupPermission> TReGroupPermissions = new HashSet<TReGroupPermission>(
			0);
	private Set<TCanvas> TCanvases = new HashSet<TCanvas>(0);

	public TGroup() {
	}

	public TGroup(String gpId) {
		this.gpId = gpId;
	}

	public TGroup(String gpId, TSystem TSystem, String gpName, Integer gpIndex,
			Integer gpColumns, Integer gpRows, Integer gpUnitHeight,
			Integer gpUnitWidth, Integer gpTop, Integer gpLeft,
			Integer gpBottom, Integer gpRight, Integer gpHeight,
			Integer gpWidth, String gpDisplay, String gpPosition,
			String gpOverflow, Integer gpLayer, Integer gpPaddingTop,
			Integer gpPaddingRight, Integer gpPaddingBottom,
			Integer gpPaddingLeft, Set<TReGroupServer> TReGroupServers,
			Set<TVideoPlay> TVideoPlays,
			Set<TBackgroundSchedule> TBackgroundSchedules,
			Set<TBackgroundPlay> TBackgroundPlays, Set<TMonitor> TMonitors,
			Set<TTemplate> TTemplates, Set<TBackground> TBackgrounds,
			Set<TVideoSchedule> TVideoSchedules,
			Set<TReGroupPermission> TReGroupPermissions, Set<TCanvas> TCanvases) {
		this.gpId = gpId;
		this.TSystem = TSystem;
		this.gpName = gpName;
		this.gpIndex = gpIndex;
		this.gpColumns = gpColumns;
		this.gpRows = gpRows;
		this.gpUnitHeight = gpUnitHeight;
		this.gpUnitWidth = gpUnitWidth;
		this.gpTop = gpTop;
		this.gpLeft = gpLeft;
		this.gpBottom = gpBottom;
		this.gpRight = gpRight;
		this.gpHeight = gpHeight;
		this.gpWidth = gpWidth;
		this.gpDisplay = gpDisplay;
		this.gpPosition = gpPosition;
		this.gpOverflow = gpOverflow;
		this.gpLayer = gpLayer;
		this.gpPaddingTop = gpPaddingTop;
		this.gpPaddingRight = gpPaddingRight;
		this.gpPaddingBottom = gpPaddingBottom;
		this.gpPaddingLeft = gpPaddingLeft;
		this.TReGroupServers = TReGroupServers;
		this.TVideoPlays = TVideoPlays;
		this.TBackgroundSchedules = TBackgroundSchedules;
		this.TBackgroundPlays = TBackgroundPlays;
		this.TMonitors = TMonitors;
		this.TTemplates = TTemplates;
		this.TBackgrounds = TBackgrounds;
		this.TVideoSchedules = TVideoSchedules;
		this.TReGroupPermissions = TReGroupPermissions;
		this.TCanvases = TCanvases;
	}

	public String getGpId() {
		return this.gpId;
	}

	public void setGpId(String gpId) {
		this.gpId = gpId;
	}

	public TSystem getTSystem() {
		return this.TSystem;
	}

	public void setTSystem(TSystem TSystem) {
		this.TSystem = TSystem;
	}

	public String getGpName() {
		return this.gpName;
	}

	public void setGpName(String gpName) {
		this.gpName = gpName;
	}

	public Integer getGpIndex() {
		return this.gpIndex;
	}

	public void setGpIndex(Integer gpIndex) {
		this.gpIndex = gpIndex;
	}

	public Integer getGpColumns() {
		return this.gpColumns;
	}

	public void setGpColumns(Integer gpColumns) {
		this.gpColumns = gpColumns;
	}

	public Integer getGpRows() {
		return this.gpRows;
	}

	public void setGpRows(Integer gpRows) {
		this.gpRows = gpRows;
	}

	public Integer getGpUnitHeight() {
		return this.gpUnitHeight;
	}

	public void setGpUnitHeight(Integer gpUnitHeight) {
		this.gpUnitHeight = gpUnitHeight;
	}

	public Integer getGpUnitWidth() {
		return this.gpUnitWidth;
	}

	public void setGpUnitWidth(Integer gpUnitWidth) {
		this.gpUnitWidth = gpUnitWidth;
	}

	public Integer getGpTop() {
		return this.gpTop;
	}

	public void setGpTop(Integer gpTop) {
		this.gpTop = gpTop;
	}

	public Integer getGpLeft() {
		return this.gpLeft;
	}

	public void setGpLeft(Integer gpLeft) {
		this.gpLeft = gpLeft;
	}

	public Integer getGpBottom() {
		return this.gpBottom;
	}

	public void setGpBottom(Integer gpBottom) {
		this.gpBottom = gpBottom;
	}

	public Integer getGpRight() {
		return this.gpRight;
	}

	public void setGpRight(Integer gpRight) {
		this.gpRight = gpRight;
	}

	public Integer getGpHeight() {
		return this.gpHeight;
	}

	public void setGpHeight(Integer gpHeight) {
		this.gpHeight = gpHeight;
	}

	public Integer getGpWidth() {
		return this.gpWidth;
	}

	public void setGpWidth(Integer gpWidth) {
		this.gpWidth = gpWidth;
	}

	public String getGpDisplay() {
		return this.gpDisplay;
	}

	public void setGpDisplay(String gpDisplay) {
		this.gpDisplay = gpDisplay;
	}

	public String getGpPosition() {
		return this.gpPosition;
	}

	public void setGpPosition(String gpPosition) {
		this.gpPosition = gpPosition;
	}

	public String getGpOverflow() {
		return this.gpOverflow;
	}

	public void setGpOverflow(String gpOverflow) {
		this.gpOverflow = gpOverflow;
	}

	public Integer getGpLayer() {
		return this.gpLayer;
	}

	public void setGpLayer(Integer gpLayer) {
		this.gpLayer = gpLayer;
	}

	public Integer getGpPaddingTop() {
		return this.gpPaddingTop;
	}

	public void setGpPaddingTop(Integer gpPaddingTop) {
		this.gpPaddingTop = gpPaddingTop;
	}

	public Integer getGpPaddingRight() {
		return this.gpPaddingRight;
	}

	public void setGpPaddingRight(Integer gpPaddingRight) {
		this.gpPaddingRight = gpPaddingRight;
	}

	public Integer getGpPaddingBottom() {
		return this.gpPaddingBottom;
	}

	public void setGpPaddingBottom(Integer gpPaddingBottom) {
		this.gpPaddingBottom = gpPaddingBottom;
	}

	public Integer getGpPaddingLeft() {
		return this.gpPaddingLeft;
	}

	public void setGpPaddingLeft(Integer gpPaddingLeft) {
		this.gpPaddingLeft = gpPaddingLeft;
	}

	public Set<TReGroupServer> getTReGroupServers() {
		return this.TReGroupServers;
	}

	public void setTReGroupServers(Set<TReGroupServer> TReGroupServers) {
		this.TReGroupServers = TReGroupServers;
	}

	public Set<TVideoPlay> getTVideoPlays() {
		return this.TVideoPlays;
	}

	public void setTVideoPlays(Set<TVideoPlay> TVideoPlays) {
		this.TVideoPlays = TVideoPlays;
	}

	public Set<TBackgroundSchedule> getTBackgroundSchedules() {
		return this.TBackgroundSchedules;
	}

	public void setTBackgroundSchedules(
			Set<TBackgroundSchedule> TBackgroundSchedules) {
		this.TBackgroundSchedules = TBackgroundSchedules;
	}

	public Set<TBackgroundPlay> getTBackgroundPlays() {
		return this.TBackgroundPlays;
	}

	public void setTBackgroundPlays(Set<TBackgroundPlay> TBackgroundPlays) {
		this.TBackgroundPlays = TBackgroundPlays;
	}

	public Set<TMonitor> getTMonitors() {
		return this.TMonitors;
	}

	public void setTMonitors(Set<TMonitor> TMonitors) {
		this.TMonitors = TMonitors;
	}

	public Set<TTemplate> getTTemplates() {
		return this.TTemplates;
	}

	public void setTTemplates(Set<TTemplate> TTemplates) {
		this.TTemplates = TTemplates;
	}

	public Set<TBackground> getTBackgrounds() {
		return this.TBackgrounds;
	}

	public void setTBackgrounds(Set<TBackground> TBackgrounds) {
		this.TBackgrounds = TBackgrounds;
	}

	public Set<TVideoSchedule> getTVideoSchedules() {
		return this.TVideoSchedules;
	}

	public void setTVideoSchedules(Set<TVideoSchedule> TVideoSchedules) {
		this.TVideoSchedules = TVideoSchedules;
	}

	public Set<TReGroupPermission> getTReGroupPermissions() {
		return this.TReGroupPermissions;
	}

	public void setTReGroupPermissions(
			Set<TReGroupPermission> TReGroupPermissions) {
		this.TReGroupPermissions = TReGroupPermissions;
	}

	public Set<TCanvas> getTCanvases() {
		return this.TCanvases;
	}

	public void setTCanvases(Set<TCanvas> TCanvases) {
		this.TCanvases = TCanvases;
	}

}
