package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TMonitor generated by hbm2java
 */
public class TMonitor implements java.io.Serializable {

	private String mntId;
	private TGroup TGroup;
	private String mntName;
	private Integer mntIndex;
	private Integer mntColumn;
	private Integer mntRow;
	private Integer mntTop;
	private Integer mntLeft;
	private Integer mntBottom;
	private Integer mntRight;
	private Integer mntHeight;
	private Integer mntWidth;
	private String mntDisplay;
	private String mntPosition;
	private String mntOverflow;
	private Integer mntLayer;
	private Integer mntPaddingTop;
	private Integer mntPaddingRight;
	private Integer mntPaddingBottom;
	private Integer mntPaddingLeft;
	private String mntBackcolor;
	private String mntCheckSourceColor;
	private String mntCheckDestColor;
	private Integer mntBacksizeHeight;
	private Integer mntBacksizeWidth;
	private Integer mntLuminance;
	private Integer mntContrast;
	private Integer mntColorTemperature;
	private Boolean mntSwitch;
	private Set<TController> TControllers = new HashSet<TController>(0);
	private Set<TBackground> TBackgrounds = new HashSet<TBackground>(0);
	private Set<TFontBackground> TFontBackgrounds = new HashSet<TFontBackground>(
			0);

	public TMonitor() {
	}

	public TMonitor(String mntId) {
		this.mntId = mntId;
	}

	public TMonitor(String mntId, TGroup TGroup, String mntName,
			Integer mntIndex, Integer mntColumn, Integer mntRow,
			Integer mntTop, Integer mntLeft, Integer mntBottom,
			Integer mntRight, Integer mntHeight, Integer mntWidth,
			String mntDisplay, String mntPosition, String mntOverflow,
			Integer mntLayer, Integer mntPaddingTop, Integer mntPaddingRight,
			Integer mntPaddingBottom, Integer mntPaddingLeft,
			String mntBackcolor, String mntCheckSourceColor,
			String mntCheckDestColor, Integer mntBacksizeHeight,
			Integer mntBacksizeWidth, Integer mntLuminance,
			Integer mntContrast, Integer mntColorTemperature,
			Boolean mntSwitch, Set<TController> TControllers,
			Set<TBackground> TBackgrounds, Set<TFontBackground> TFontBackgrounds) {
		this.mntId = mntId;
		this.TGroup = TGroup;
		this.mntName = mntName;
		this.mntIndex = mntIndex;
		this.mntColumn = mntColumn;
		this.mntRow = mntRow;
		this.mntTop = mntTop;
		this.mntLeft = mntLeft;
		this.mntBottom = mntBottom;
		this.mntRight = mntRight;
		this.mntHeight = mntHeight;
		this.mntWidth = mntWidth;
		this.mntDisplay = mntDisplay;
		this.mntPosition = mntPosition;
		this.mntOverflow = mntOverflow;
		this.mntLayer = mntLayer;
		this.mntPaddingTop = mntPaddingTop;
		this.mntPaddingRight = mntPaddingRight;
		this.mntPaddingBottom = mntPaddingBottom;
		this.mntPaddingLeft = mntPaddingLeft;
		this.mntBackcolor = mntBackcolor;
		this.mntCheckSourceColor = mntCheckSourceColor;
		this.mntCheckDestColor = mntCheckDestColor;
		this.mntBacksizeHeight = mntBacksizeHeight;
		this.mntBacksizeWidth = mntBacksizeWidth;
		this.mntLuminance = mntLuminance;
		this.mntContrast = mntContrast;
		this.mntColorTemperature = mntColorTemperature;
		this.mntSwitch = mntSwitch;
		this.TControllers = TControllers;
		this.TBackgrounds = TBackgrounds;
		this.TFontBackgrounds = TFontBackgrounds;
	}

	public String getMntId() {
		return this.mntId;
	}

	public void setMntId(String mntId) {
		this.mntId = mntId;
	}

	public TGroup getTGroup() {
		return this.TGroup;
	}

	public void setTGroup(TGroup TGroup) {
		this.TGroup = TGroup;
	}

	public String getMntName() {
		return this.mntName;
	}

	public void setMntName(String mntName) {
		this.mntName = mntName;
	}

	public Integer getMntIndex() {
		return this.mntIndex;
	}

	public void setMntIndex(Integer mntIndex) {
		this.mntIndex = mntIndex;
	}

	public Integer getMntColumn() {
		return this.mntColumn;
	}

	public void setMntColumn(Integer mntColumn) {
		this.mntColumn = mntColumn;
	}

	public Integer getMntRow() {
		return this.mntRow;
	}

	public void setMntRow(Integer mntRow) {
		this.mntRow = mntRow;
	}

	public Integer getMntTop() {
		return this.mntTop;
	}

	public void setMntTop(Integer mntTop) {
		this.mntTop = mntTop;
	}

	public Integer getMntLeft() {
		return this.mntLeft;
	}

	public void setMntLeft(Integer mntLeft) {
		this.mntLeft = mntLeft;
	}

	public Integer getMntBottom() {
		return this.mntBottom;
	}

	public void setMntBottom(Integer mntBottom) {
		this.mntBottom = mntBottom;
	}

	public Integer getMntRight() {
		return this.mntRight;
	}

	public void setMntRight(Integer mntRight) {
		this.mntRight = mntRight;
	}

	public Integer getMntHeight() {
		return this.mntHeight;
	}

	public void setMntHeight(Integer mntHeight) {
		this.mntHeight = mntHeight;
	}

	public Integer getMntWidth() {
		return this.mntWidth;
	}

	public void setMntWidth(Integer mntWidth) {
		this.mntWidth = mntWidth;
	}

	public String getMntDisplay() {
		return this.mntDisplay;
	}

	public void setMntDisplay(String mntDisplay) {
		this.mntDisplay = mntDisplay;
	}

	public String getMntPosition() {
		return this.mntPosition;
	}

	public void setMntPosition(String mntPosition) {
		this.mntPosition = mntPosition;
	}

	public String getMntOverflow() {
		return this.mntOverflow;
	}

	public void setMntOverflow(String mntOverflow) {
		this.mntOverflow = mntOverflow;
	}

	public Integer getMntLayer() {
		return this.mntLayer;
	}

	public void setMntLayer(Integer mntLayer) {
		this.mntLayer = mntLayer;
	}

	public Integer getMntPaddingTop() {
		return this.mntPaddingTop;
	}

	public void setMntPaddingTop(Integer mntPaddingTop) {
		this.mntPaddingTop = mntPaddingTop;
	}

	public Integer getMntPaddingRight() {
		return this.mntPaddingRight;
	}

	public void setMntPaddingRight(Integer mntPaddingRight) {
		this.mntPaddingRight = mntPaddingRight;
	}

	public Integer getMntPaddingBottom() {
		return this.mntPaddingBottom;
	}

	public void setMntPaddingBottom(Integer mntPaddingBottom) {
		this.mntPaddingBottom = mntPaddingBottom;
	}

	public Integer getMntPaddingLeft() {
		return this.mntPaddingLeft;
	}

	public void setMntPaddingLeft(Integer mntPaddingLeft) {
		this.mntPaddingLeft = mntPaddingLeft;
	}

	public String getMntBackcolor() {
		return this.mntBackcolor;
	}

	public void setMntBackcolor(String mntBackcolor) {
		this.mntBackcolor = mntBackcolor;
	}

	public String getMntCheckSourceColor() {
		return this.mntCheckSourceColor;
	}

	public void setMntCheckSourceColor(String mntCheckSourceColor) {
		this.mntCheckSourceColor = mntCheckSourceColor;
	}

	public String getMntCheckDestColor() {
		return this.mntCheckDestColor;
	}

	public void setMntCheckDestColor(String mntCheckDestColor) {
		this.mntCheckDestColor = mntCheckDestColor;
	}

	public Integer getMntBacksizeHeight() {
		return this.mntBacksizeHeight;
	}

	public void setMntBacksizeHeight(Integer mntBacksizeHeight) {
		this.mntBacksizeHeight = mntBacksizeHeight;
	}

	public Integer getMntBacksizeWidth() {
		return this.mntBacksizeWidth;
	}

	public void setMntBacksizeWidth(Integer mntBacksizeWidth) {
		this.mntBacksizeWidth = mntBacksizeWidth;
	}

	public Integer getMntLuminance() {
		return this.mntLuminance;
	}

	public void setMntLuminance(Integer mntLuminance) {
		this.mntLuminance = mntLuminance;
	}

	public Integer getMntContrast() {
		return this.mntContrast;
	}

	public void setMntContrast(Integer mntContrast) {
		this.mntContrast = mntContrast;
	}

	public Integer getMntColorTemperature() {
		return this.mntColorTemperature;
	}

	public void setMntColorTemperature(Integer mntColorTemperature) {
		this.mntColorTemperature = mntColorTemperature;
	}

	public Boolean getMntSwitch() {
		return this.mntSwitch;
	}

	public void setMntSwitch(Boolean mntSwitch) {
		this.mntSwitch = mntSwitch;
	}

	public Set<TController> getTControllers() {
		return this.TControllers;
	}

	public void setTControllers(Set<TController> TControllers) {
		this.TControllers = TControllers;
	}

	public Set<TBackground> getTBackgrounds() {
		return this.TBackgrounds;
	}

	public void setTBackgrounds(Set<TBackground> TBackgrounds) {
		this.TBackgrounds = TBackgrounds;
	}

	public Set<TFontBackground> getTFontBackgrounds() {
		return this.TFontBackgrounds;
	}

	public void setTFontBackgrounds(Set<TFontBackground> TFontBackgrounds) {
		this.TFontBackgrounds = TFontBackgrounds;
	}

}
