package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

/**
 * TReGroupPermission generated by hbm2java
 */
public class TReGroupPermission implements java.io.Serializable {

	private Integer rgpId;
	private TUser TUser;
	private TGroup TGroup;
	private TUserGroup TUserGroup;
	private boolean ugpGet;
	private boolean ugpSet;
	private String ugpBackground;
	private String ugpFont;

	public TReGroupPermission() {
	}

	public TReGroupPermission(boolean ugpGet, boolean ugpSet) {
		this.ugpGet = ugpGet;
		this.ugpSet = ugpSet;
	}

	public TReGroupPermission(TUser TUser, TGroup TGroup,
			TUserGroup TUserGroup, boolean ugpGet, boolean ugpSet,
			String ugpBackground, String ugpFont) {
		this.TUser = TUser;
		this.TGroup = TGroup;
		this.TUserGroup = TUserGroup;
		this.ugpGet = ugpGet;
		this.ugpSet = ugpSet;
		this.ugpBackground = ugpBackground;
		this.ugpFont = ugpFont;
	}

	public Integer getRgpId() {
		return this.rgpId;
	}

	public void setRgpId(Integer rgpId) {
		this.rgpId = rgpId;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public TGroup getTGroup() {
		return this.TGroup;
	}

	public void setTGroup(TGroup TGroup) {
		this.TGroup = TGroup;
	}

	public TUserGroup getTUserGroup() {
		return this.TUserGroup;
	}

	public void setTUserGroup(TUserGroup TUserGroup) {
		this.TUserGroup = TUserGroup;
	}

	public boolean isUgpGet() {
		return this.ugpGet;
	}

	public void setUgpGet(boolean ugpGet) {
		this.ugpGet = ugpGet;
	}

	public boolean isUgpSet() {
		return this.ugpSet;
	}

	public void setUgpSet(boolean ugpSet) {
		this.ugpSet = ugpSet;
	}

	public String getUgpBackground() {
		return this.ugpBackground;
	}

	public void setUgpBackground(String ugpBackground) {
		this.ugpBackground = ugpBackground;
	}

	public String getUgpFont() {
		return this.ugpFont;
	}

	public void setUgpFont(String ugpFont) {
		this.ugpFont = ugpFont;
	}

}
