package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

/**
 * TReGroupServer generated by hbm2java
 */
public class TReGroupServer implements java.io.Serializable {

	private Integer rgsId;
	private TGroup TGroup;
	private TServer TServer;

	public TReGroupServer() {
	}

	public TReGroupServer(TGroup TGroup, TServer TServer) {
		this.TGroup = TGroup;
		this.TServer = TServer;
	}

	public Integer getRgsId() {
		return this.rgsId;
	}

	public void setRgsId(Integer rgsId) {
		this.rgsId = rgsId;
	}

	public TGroup getTGroup() {
		return this.TGroup;
	}

	public void setTGroup(TGroup TGroup) {
		this.TGroup = TGroup;
	}

	public TServer getTServer() {
		return this.TServer;
	}

	public void setTServer(TServer TServer) {
		this.TServer = TServer;
	}

}
