package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

/**
 * TRePlayPermission generated by hbm2java
 */
public class TRePlayPermission implements java.io.Serializable {

	private Integer rppId;
	private TVideoPlay TVideoPlay;
	private TUser TUser;
	private TUserGroup TUserGroup;
	private String uppPosition;

	public TRePlayPermission() {
	}

	public TRePlayPermission(TVideoPlay TVideoPlay, TUser TUser,
			TUserGroup TUserGroup, String uppPosition) {
		this.TVideoPlay = TVideoPlay;
		this.TUser = TUser;
		this.TUserGroup = TUserGroup;
		this.uppPosition = uppPosition;
	}

	public Integer getRppId() {
		return this.rppId;
	}

	public void setRppId(Integer rppId) {
		this.rppId = rppId;
	}

	public TVideoPlay getTVideoPlay() {
		return this.TVideoPlay;
	}

	public void setTVideoPlay(TVideoPlay TVideoPlay) {
		this.TVideoPlay = TVideoPlay;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public TUserGroup getTUserGroup() {
		return this.TUserGroup;
	}

	public void setTUserGroup(TUserGroup TUserGroup) {
		this.TUserGroup = TUserGroup;
	}

	public String getUppPosition() {
		return this.uppPosition;
	}

	public void setUppPosition(String uppPosition) {
		this.uppPosition = uppPosition;
	}

}
