package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

/**
 * TReResourcePermission generated by hbm2java
 */
public class TReResourcePermission implements java.io.Serializable {

	private Integer rrpId;
	private TResource TResource;
	private TUser TUser;
	private TUserGroup TUserGroup;
	private boolean urpGet;
	private boolean urpSet;

	public TReResourcePermission() {
	}

	public TReResourcePermission(boolean urpGet, boolean urpSet) {
		this.urpGet = urpGet;
		this.urpSet = urpSet;
	}

	public TReResourcePermission(TResource TResource, TUser TUser,
			TUserGroup TUserGroup, boolean urpGet, boolean urpSet) {
		this.TResource = TResource;
		this.TUser = TUser;
		this.TUserGroup = TUserGroup;
		this.urpGet = urpGet;
		this.urpSet = urpSet;
	}

	public Integer getRrpId() {
		return this.rrpId;
	}

	public void setRrpId(Integer rrpId) {
		this.rrpId = rrpId;
	}

	public TResource getTResource() {
		return this.TResource;
	}

	public void setTResource(TResource TResource) {
		this.TResource = TResource;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public TUserGroup getTUserGroup() {
		return this.TUserGroup;
	}

	public void setTUserGroup(TUserGroup TUserGroup) {
		this.TUserGroup = TUserGroup;
	}

	public boolean isUrpGet() {
		return this.urpGet;
	}

	public void setUrpGet(boolean urpGet) {
		this.urpGet = urpGet;
	}

	public boolean isUrpSet() {
		return this.urpSet;
	}

	public void setUrpSet(boolean urpSet) {
		this.urpSet = urpSet;
	}

}
