package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

/**
 * TReUsrgPermission generated by hbm2java
 */
public class TReUsrgPermission implements java.io.Serializable {

	private Integer rupId;
	private TUser TUser;
	private TUserGroup TUserGroup;
	private Boolean usrgIsCreateGroup;
	private Boolean usrgIsRoot;
	private Boolean usrgIsCreateUsrg;
	private Boolean usrgIsDeleteUsrg;
	private Boolean usrgIsQueryUsrg;
	private Boolean usrgIsUpdateUsrg;

	public TReUsrgPermission() {
	}

	public TReUsrgPermission(TUser TUser, TUserGroup TUserGroup,
			Boolean usrgIsCreateGroup, Boolean usrgIsRoot,
			Boolean usrgIsCreateUsrg, Boolean usrgIsDeleteUsrg,
			Boolean usrgIsQueryUsrg, Boolean usrgIsUpdateUsrg) {
		this.TUser = TUser;
		this.TUserGroup = TUserGroup;
		this.usrgIsCreateGroup = usrgIsCreateGroup;
		this.usrgIsRoot = usrgIsRoot;
		this.usrgIsCreateUsrg = usrgIsCreateUsrg;
		this.usrgIsDeleteUsrg = usrgIsDeleteUsrg;
		this.usrgIsQueryUsrg = usrgIsQueryUsrg;
		this.usrgIsUpdateUsrg = usrgIsUpdateUsrg;
	}

	public Integer getRupId() {
		return this.rupId;
	}

	public void setRupId(Integer rupId) {
		this.rupId = rupId;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public TUserGroup getTUserGroup() {
		return this.TUserGroup;
	}

	public void setTUserGroup(TUserGroup TUserGroup) {
		this.TUserGroup = TUserGroup;
	}

	public Boolean getUsrgIsCreateGroup() {
		return this.usrgIsCreateGroup;
	}

	public void setUsrgIsCreateGroup(Boolean usrgIsCreateGroup) {
		this.usrgIsCreateGroup = usrgIsCreateGroup;
	}

	public Boolean getUsrgIsRoot() {
		return this.usrgIsRoot;
	}

	public void setUsrgIsRoot(Boolean usrgIsRoot) {
		this.usrgIsRoot = usrgIsRoot;
	}

	public Boolean getUsrgIsCreateUsrg() {
		return this.usrgIsCreateUsrg;
	}

	public void setUsrgIsCreateUsrg(Boolean usrgIsCreateUsrg) {
		this.usrgIsCreateUsrg = usrgIsCreateUsrg;
	}

	public Boolean getUsrgIsDeleteUsrg() {
		return this.usrgIsDeleteUsrg;
	}

	public void setUsrgIsDeleteUsrg(Boolean usrgIsDeleteUsrg) {
		this.usrgIsDeleteUsrg = usrgIsDeleteUsrg;
	}

	public Boolean getUsrgIsQueryUsrg() {
		return this.usrgIsQueryUsrg;
	}

	public void setUsrgIsQueryUsrg(Boolean usrgIsQueryUsrg) {
		this.usrgIsQueryUsrg = usrgIsQueryUsrg;
	}

	public Boolean getUsrgIsUpdateUsrg() {
		return this.usrgIsUpdateUsrg;
	}

	public void setUsrgIsUpdateUsrg(Boolean usrgIsUpdateUsrg) {
		this.usrgIsUpdateUsrg = usrgIsUpdateUsrg;
	}

}
