package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

/**
 * TReVedioSchedulePermission generated by hbm2java
 */
public class TReVedioSchedulePermission implements java.io.Serializable {

	private Integer rvspId;
	private TUser TUser;
	private TUserGroup TUserGroup;
	private TVideoSchedule TVideoSchedule;
	private boolean uvspSet;
	private boolean uvspGet;

	public TReVedioSchedulePermission() {
	}

	public TReVedioSchedulePermission(boolean uvspSet, boolean uvspGet) {
		this.uvspSet = uvspSet;
		this.uvspGet = uvspGet;
	}

	public TReVedioSchedulePermission(TUser TUser, TUserGroup TUserGroup,
			TVideoSchedule TVideoSchedule, boolean uvspSet, boolean uvspGet) {
		this.TUser = TUser;
		this.TUserGroup = TUserGroup;
		this.TVideoSchedule = TVideoSchedule;
		this.uvspSet = uvspSet;
		this.uvspGet = uvspGet;
	}

	public Integer getRvspId() {
		return this.rvspId;
	}

	public void setRvspId(Integer rvspId) {
		this.rvspId = rvspId;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public TUserGroup getTUserGroup() {
		return this.TUserGroup;
	}

	public void setTUserGroup(TUserGroup TUserGroup) {
		this.TUserGroup = TUserGroup;
	}

	public TVideoSchedule getTVideoSchedule() {
		return this.TVideoSchedule;
	}

	public void setTVideoSchedule(TVideoSchedule TVideoSchedule) {
		this.TVideoSchedule = TVideoSchedule;
	}

	public boolean isUvspSet() {
		return this.uvspSet;
	}

	public void setUvspSet(boolean uvspSet) {
		this.uvspSet = uvspSet;
	}

	public boolean isUvspGet() {
		return this.uvspGet;
	}

	public void setUvspGet(boolean uvspGet) {
		this.uvspGet = uvspGet;
	}

}
