package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TRootResource generated by hbm2java
 */
public class TRootResource implements java.io.Serializable {

	private String rrsId;
	private TSystem TSystem;
	private TServer TServer;
	private Integer rrsType;
	private String rrsParent;
	private String rrsName;
	private String rrsShowName;
	private String rrsIp;
	private String rrsAddr;
	private Integer rrsStatus;
	private Integer rrsFps;
	private Integer rrsBps;
	private Set<TResource> TResources = new HashSet<TResource>(0);

	public TRootResource() {
	}

	public TRootResource(String rrsId) {
		this.rrsId = rrsId;
	}

	public TRootResource(String rrsId, TSystem TSystem, TServer TServer,
			Integer rrsType, String rrsParent, String rrsName,
			String rrsShowName, String rrsIp, String rrsAddr,
			Integer rrsStatus, Integer rrsFps, Integer rrsBps,
			Set<TResource> TResources) {
		this.rrsId = rrsId;
		this.TSystem = TSystem;
		this.TServer = TServer;
		this.rrsType = rrsType;
		this.rrsParent = rrsParent;
		this.rrsName = rrsName;
		this.rrsShowName = rrsShowName;
		this.rrsIp = rrsIp;
		this.rrsAddr = rrsAddr;
		this.rrsStatus = rrsStatus;
		this.rrsFps = rrsFps;
		this.rrsBps = rrsBps;
		this.TResources = TResources;
	}

	public String getRrsId() {
		return this.rrsId;
	}

	public void setRrsId(String rrsId) {
		this.rrsId = rrsId;
	}

	public TSystem getTSystem() {
		return this.TSystem;
	}

	public void setTSystem(TSystem TSystem) {
		this.TSystem = TSystem;
	}

	public TServer getTServer() {
		return this.TServer;
	}

	public void setTServer(TServer TServer) {
		this.TServer = TServer;
	}

	public Integer getRrsType() {
		return this.rrsType;
	}

	public void setRrsType(Integer rrsType) {
		this.rrsType = rrsType;
	}

	public String getRrsParent() {
		return this.rrsParent;
	}

	public void setRrsParent(String rrsParent) {
		this.rrsParent = rrsParent;
	}

	public String getRrsName() {
		return this.rrsName;
	}

	public void setRrsName(String rrsName) {
		this.rrsName = rrsName;
	}

	public String getRrsShowName() {
		return this.rrsShowName;
	}

	public void setRrsShowName(String rrsShowName) {
		this.rrsShowName = rrsShowName;
	}

	public String getRrsIp() {
		return this.rrsIp;
	}

	public void setRrsIp(String rrsIp) {
		this.rrsIp = rrsIp;
	}

	public String getRrsAddr() {
		return this.rrsAddr;
	}

	public void setRrsAddr(String rrsAddr) {
		this.rrsAddr = rrsAddr;
	}

	public Integer getRrsStatus() {
		return this.rrsStatus;
	}

	public void setRrsStatus(Integer rrsStatus) {
		this.rrsStatus = rrsStatus;
	}

	public Integer getRrsFps() {
		return this.rrsFps;
	}

	public void setRrsFps(Integer rrsFps) {
		this.rrsFps = rrsFps;
	}

	public Integer getRrsBps() {
		return this.rrsBps;
	}

	public void setRrsBps(Integer rrsBps) {
		this.rrsBps = rrsBps;
	}

	public Set<TResource> getTResources() {
		return this.TResources;
	}

	public void setTResources(Set<TResource> TResources) {
		this.TResources = TResources;
	}

}
