package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TSystemExceptionLog generated by hbm2java
 */
public class TSystemExceptionLog implements java.io.Serializable {

	private Integer seIndex;
	private Date seTime;
	private Integer seType;
	private String seLevel;
	private String seComment;

	public TSystemExceptionLog() {
	}

	public TSystemExceptionLog(Date seTime, Integer seType, String seLevel,
			String seComment) {
		this.seTime = seTime;
		this.seType = seType;
		this.seLevel = seLevel;
		this.seComment = seComment;
	}

	public Integer getSeIndex() {
		return this.seIndex;
	}

	public void setSeIndex(Integer seIndex) {
		this.seIndex = seIndex;
	}

	public Date getSeTime() {
		return this.seTime;
	}

	public void setSeTime(Date seTime) {
		this.seTime = seTime;
	}

	public Integer getSeType() {
		return this.seType;
	}

	public void setSeType(Integer seType) {
		this.seType = seType;
	}

	public String getSeLevel() {
		return this.seLevel;
	}

	public void setSeLevel(String seLevel) {
		this.seLevel = seLevel;
	}

	public String getSeComment() {
		return this.seComment;
	}

	public void setSeComment(String seComment) {
		this.seComment = seComment;
	}

}
