package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TSystemLog generated by hbm2java
 */
public class TSystemLog implements java.io.Serializable {

	private Integer slIndex;
	private Date slTime;
	private Integer slType;
	private String slLevel;
	private String slComment;

	public TSystemLog() {
	}

	public TSystemLog(Date slTime, Integer slType, String slLevel,
			String slComment) {
		this.slTime = slTime;
		this.slType = slType;
		this.slLevel = slLevel;
		this.slComment = slComment;
	}

	public Integer getSlIndex() {
		return this.slIndex;
	}

	public void setSlIndex(Integer slIndex) {
		this.slIndex = slIndex;
	}

	public Date getSlTime() {
		return this.slTime;
	}

	public void setSlTime(Date slTime) {
		this.slTime = slTime;
	}

	public Integer getSlType() {
		return this.slType;
	}

	public void setSlType(Integer slType) {
		this.slType = slType;
	}

	public String getSlLevel() {
		return this.slLevel;
	}

	public void setSlLevel(String slLevel) {
		this.slLevel = slLevel;
	}

	public String getSlComment() {
		return this.slComment;
	}

	public void setSlComment(String slComment) {
		this.slComment = slComment;
	}

}
