package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TSystem generated by hbm2java
 */
public class TSystem implements java.io.Serializable {

	private String sysId;
	private TGateway TGateway;
	private TDeviceType TDeviceType;
	private String cssId;
	private String sysName;
	private Integer sysStatus;
	private String sysIp;
	private String sysNetwork;
	private String sysMac;
	private Integer sysUdpPort;
	private Integer sysTcpPort;
	private Date sysRegistTime;
	private String sysVersion;
	private Set<TGroup> TGroups = new HashSet<TGroup>(0);
	private Set<TServer> TServers = new HashSet<TServer>(0);
	private Set<TRootResource> TRootResources = new HashSet<TRootResource>(0);
	private Set<TController> TControllers = new HashSet<TController>(0);

	public TSystem() {
	}

	public TSystem(String sysId) {
		this.sysId = sysId;
	}

	public TSystem(String sysId, TGateway TGateway, TDeviceType TDeviceType,
			String cssId, String sysName, Integer sysStatus, String sysIp,
			String sysNetwork, String sysMac, Integer sysUdpPort,
			Integer sysTcpPort, Date sysRegistTime, String sysVersion,
			Set<TGroup> TGroups, Set<TServer> TServers,
			Set<TRootResource> TRootResources, Set<TController> TControllers) {
		this.sysId = sysId;
		this.TGateway = TGateway;
		this.TDeviceType = TDeviceType;
		this.cssId = cssId;
		this.sysName = sysName;
		this.sysStatus = sysStatus;
		this.sysIp = sysIp;
		this.sysNetwork = sysNetwork;
		this.sysMac = sysMac;
		this.sysUdpPort = sysUdpPort;
		this.sysTcpPort = sysTcpPort;
		this.sysRegistTime = sysRegistTime;
		this.sysVersion = sysVersion;
		this.TGroups = TGroups;
		this.TServers = TServers;
		this.TRootResources = TRootResources;
		this.TControllers = TControllers;
	}

	public String getSysId() {
		return this.sysId;
	}

	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	public TGateway getTGateway() {
		return this.TGateway;
	}

	public void setTGateway(TGateway TGateway) {
		this.TGateway = TGateway;
	}

	public TDeviceType getTDeviceType() {
		return this.TDeviceType;
	}

	public void setTDeviceType(TDeviceType TDeviceType) {
		this.TDeviceType = TDeviceType;
	}

	public String getCssId() {
		return this.cssId;
	}

	public void setCssId(String cssId) {
		this.cssId = cssId;
	}

	public String getSysName() {
		return this.sysName;
	}

	public void setSysName(String sysName) {
		this.sysName = sysName;
	}

	public Integer getSysStatus() {
		return this.sysStatus;
	}

	public void setSysStatus(Integer sysStatus) {
		this.sysStatus = sysStatus;
	}

	public String getSysIp() {
		return this.sysIp;
	}

	public void setSysIp(String sysIp) {
		this.sysIp = sysIp;
	}

	public String getSysNetwork() {
		return this.sysNetwork;
	}

	public void setSysNetwork(String sysNetwork) {
		this.sysNetwork = sysNetwork;
	}

	public String getSysMac() {
		return this.sysMac;
	}

	public void setSysMac(String sysMac) {
		this.sysMac = sysMac;
	}

	public Integer getSysUdpPort() {
		return this.sysUdpPort;
	}

	public void setSysUdpPort(Integer sysUdpPort) {
		this.sysUdpPort = sysUdpPort;
	}

	public Integer getSysTcpPort() {
		return this.sysTcpPort;
	}

	public void setSysTcpPort(Integer sysTcpPort) {
		this.sysTcpPort = sysTcpPort;
	}

	public Date getSysRegistTime() {
		return this.sysRegistTime;
	}

	public void setSysRegistTime(Date sysRegistTime) {
		this.sysRegistTime = sysRegistTime;
	}

	public String getSysVersion() {
		return this.sysVersion;
	}

	public void setSysVersion(String sysVersion) {
		this.sysVersion = sysVersion;
	}

	public Set<TGroup> getTGroups() {
		return this.TGroups;
	}

	public void setTGroups(Set<TGroup> TGroups) {
		this.TGroups = TGroups;
	}

	public Set<TServer> getTServers() {
		return this.TServers;
	}

	public void setTServers(Set<TServer> TServers) {
		this.TServers = TServers;
	}

	public Set<TRootResource> getTRootResources() {
		return this.TRootResources;
	}

	public void setTRootResources(Set<TRootResource> TRootResources) {
		this.TRootResources = TRootResources;
	}

	public Set<TController> getTControllers() {
		return this.TControllers;
	}

	public void setTControllers(Set<TController> TControllers) {
		this.TControllers = TControllers;
	}

}
