package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TTemplate generated by hbm2java
 */
public class TTemplate implements java.io.Serializable {

	private String tpId;
	private TGroup TGroup;
	private String tpName;
	private Integer tpIndex;
	private Integer tpColumns;
	private Integer tpRows;
	private Integer tpTop;
	private Integer tpLeft;
	private Integer tpBottom;
	private Integer tpRight;
	private Integer tpHeight;
	private Integer tpWidth;
	private String tpDisplay;
	private String tpPosition;
	private String tpOverflow;
	private Integer tpLayer;
	private Integer tpPaddingTop;
	private Integer tpPaddingRight;
	private Integer tpPaddingBottom;
	private Integer tpPaddingLeft;
	private Set<TDivision> TDivisions = new HashSet<TDivision>(0);

	public TTemplate() {
	}

	public TTemplate(String tpId) {
		this.tpId = tpId;
	}

	public TTemplate(String tpId, TGroup TGroup, String tpName,
			Integer tpIndex, Integer tpColumns, Integer tpRows, Integer tpTop,
			Integer tpLeft, Integer tpBottom, Integer tpRight,
			Integer tpHeight, Integer tpWidth, String tpDisplay,
			String tpPosition, String tpOverflow, Integer tpLayer,
			Integer tpPaddingTop, Integer tpPaddingRight,
			Integer tpPaddingBottom, Integer tpPaddingLeft,
			Set<TDivision> TDivisions) {
		this.tpId = tpId;
		this.TGroup = TGroup;
		this.tpName = tpName;
		this.tpIndex = tpIndex;
		this.tpColumns = tpColumns;
		this.tpRows = tpRows;
		this.tpTop = tpTop;
		this.tpLeft = tpLeft;
		this.tpBottom = tpBottom;
		this.tpRight = tpRight;
		this.tpHeight = tpHeight;
		this.tpWidth = tpWidth;
		this.tpDisplay = tpDisplay;
		this.tpPosition = tpPosition;
		this.tpOverflow = tpOverflow;
		this.tpLayer = tpLayer;
		this.tpPaddingTop = tpPaddingTop;
		this.tpPaddingRight = tpPaddingRight;
		this.tpPaddingBottom = tpPaddingBottom;
		this.tpPaddingLeft = tpPaddingLeft;
		this.TDivisions = TDivisions;
	}

	public String getTpId() {
		return this.tpId;
	}

	public void setTpId(String tpId) {
		this.tpId = tpId;
	}

	public TGroup getTGroup() {
		return this.TGroup;
	}

	public void setTGroup(TGroup TGroup) {
		this.TGroup = TGroup;
	}

	public String getTpName() {
		return this.tpName;
	}

	public void setTpName(String tpName) {
		this.tpName = tpName;
	}

	public Integer getTpIndex() {
		return this.tpIndex;
	}

	public void setTpIndex(Integer tpIndex) {
		this.tpIndex = tpIndex;
	}

	public Integer getTpColumns() {
		return this.tpColumns;
	}

	public void setTpColumns(Integer tpColumns) {
		this.tpColumns = tpColumns;
	}

	public Integer getTpRows() {
		return this.tpRows;
	}

	public void setTpRows(Integer tpRows) {
		this.tpRows = tpRows;
	}

	public Integer getTpTop() {
		return this.tpTop;
	}

	public void setTpTop(Integer tpTop) {
		this.tpTop = tpTop;
	}

	public Integer getTpLeft() {
		return this.tpLeft;
	}

	public void setTpLeft(Integer tpLeft) {
		this.tpLeft = tpLeft;
	}

	public Integer getTpBottom() {
		return this.tpBottom;
	}

	public void setTpBottom(Integer tpBottom) {
		this.tpBottom = tpBottom;
	}

	public Integer getTpRight() {
		return this.tpRight;
	}

	public void setTpRight(Integer tpRight) {
		this.tpRight = tpRight;
	}

	public Integer getTpHeight() {
		return this.tpHeight;
	}

	public void setTpHeight(Integer tpHeight) {
		this.tpHeight = tpHeight;
	}

	public Integer getTpWidth() {
		return this.tpWidth;
	}

	public void setTpWidth(Integer tpWidth) {
		this.tpWidth = tpWidth;
	}

	public String getTpDisplay() {
		return this.tpDisplay;
	}

	public void setTpDisplay(String tpDisplay) {
		this.tpDisplay = tpDisplay;
	}

	public String getTpPosition() {
		return this.tpPosition;
	}

	public void setTpPosition(String tpPosition) {
		this.tpPosition = tpPosition;
	}

	public String getTpOverflow() {
		return this.tpOverflow;
	}

	public void setTpOverflow(String tpOverflow) {
		this.tpOverflow = tpOverflow;
	}

	public Integer getTpLayer() {
		return this.tpLayer;
	}

	public void setTpLayer(Integer tpLayer) {
		this.tpLayer = tpLayer;
	}

	public Integer getTpPaddingTop() {
		return this.tpPaddingTop;
	}

	public void setTpPaddingTop(Integer tpPaddingTop) {
		this.tpPaddingTop = tpPaddingTop;
	}

	public Integer getTpPaddingRight() {
		return this.tpPaddingRight;
	}

	public void setTpPaddingRight(Integer tpPaddingRight) {
		this.tpPaddingRight = tpPaddingRight;
	}

	public Integer getTpPaddingBottom() {
		return this.tpPaddingBottom;
	}

	public void setTpPaddingBottom(Integer tpPaddingBottom) {
		this.tpPaddingBottom = tpPaddingBottom;
	}

	public Integer getTpPaddingLeft() {
		return this.tpPaddingLeft;
	}

	public void setTpPaddingLeft(Integer tpPaddingLeft) {
		this.tpPaddingLeft = tpPaddingLeft;
	}

	public Set<TDivision> getTDivisions() {
		return this.TDivisions;
	}

	public void setTDivisions(Set<TDivision> TDivisions) {
		this.TDivisions = TDivisions;
	}

}
