package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TUserLog generated by hbm2java
 */
public class TUserLog implements java.io.Serializable {

	private Integer ulIndex;
	private Date ulTime;
	private Integer ulType;
	private String ulLevel;
	private String ulComment;

	public TUserLog() {
	}

	public TUserLog(Date ulTime, Integer ulType, String ulLevel,
			String ulComment) {
		this.ulTime = ulTime;
		this.ulType = ulType;
		this.ulLevel = ulLevel;
		this.ulComment = ulComment;
	}

	public Integer getUlIndex() {
		return this.ulIndex;
	}

	public void setUlIndex(Integer ulIndex) {
		this.ulIndex = ulIndex;
	}

	public Date getUlTime() {
		return this.ulTime;
	}

	public void setUlTime(Date ulTime) {
		this.ulTime = ulTime;
	}

	public Integer getUlType() {
		return this.ulType;
	}

	public void setUlType(Integer ulType) {
		this.ulType = ulType;
	}

	public String getUlLevel() {
		return this.ulLevel;
	}

	public void setUlLevel(String ulLevel) {
		this.ulLevel = ulLevel;
	}

	public String getUlComment() {
		return this.ulComment;
	}

	public void setUlComment(String ulComment) {
		this.ulComment = ulComment;
	}

}
