package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TUserGroup generated by hbm2java
 */
public class TUserGroup implements java.io.Serializable {

	private String usgId;
	private String usgName;
	private String usgDescription;
	private Date usgCreateTime;
	private Set<TUser> TUsers = new HashSet<TUser>(0);
	private Set<TRePlayPermission> TRePlayPermissions = new HashSet<TRePlayPermission>(
			0);
	private Set<TReResourcePermission> TReResourcePermissions = new HashSet<TReResourcePermission>(
			0);
	private Set<TReUsrgPermission> TReUsrgPermissions = new HashSet<TReUsrgPermission>(
			0);
	private Set<TReVedioSchedulePermission> TReVedioSchedulePermissions = new HashSet<TReVedioSchedulePermission>(
			0);
	private Set<TReGroupPermission> TReGroupPermissions = new HashSet<TReGroupPermission>(
			0);

	public TUserGroup() {
	}

	public TUserGroup(String usgId) {
		this.usgId = usgId;
	}

	public TUserGroup(String usgId, String usgName, String usgDescription,
			Date usgCreateTime, Set<TUser> TUsers,
			Set<TRePlayPermission> TRePlayPermissions,
			Set<TReResourcePermission> TReResourcePermissions,
			Set<TReUsrgPermission> TReUsrgPermissions,
			Set<TReVedioSchedulePermission> TReVedioSchedulePermissions,
			Set<TReGroupPermission> TReGroupPermissions) {
		this.usgId = usgId;
		this.usgName = usgName;
		this.usgDescription = usgDescription;
		this.usgCreateTime = usgCreateTime;
		this.TUsers = TUsers;
		this.TRePlayPermissions = TRePlayPermissions;
		this.TReResourcePermissions = TReResourcePermissions;
		this.TReUsrgPermissions = TReUsrgPermissions;
		this.TReVedioSchedulePermissions = TReVedioSchedulePermissions;
		this.TReGroupPermissions = TReGroupPermissions;
	}

	public String getUsgId() {
		return this.usgId;
	}

	public void setUsgId(String usgId) {
		this.usgId = usgId;
	}

	public String getUsgName() {
		return this.usgName;
	}

	public void setUsgName(String usgName) {
		this.usgName = usgName;
	}

	public String getUsgDescription() {
		return this.usgDescription;
	}

	public void setUsgDescription(String usgDescription) {
		this.usgDescription = usgDescription;
	}

	public Date getUsgCreateTime() {
		return this.usgCreateTime;
	}

	public void setUsgCreateTime(Date usgCreateTime) {
		this.usgCreateTime = usgCreateTime;
	}

	public Set<TUser> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<TUser> TUsers) {
		this.TUsers = TUsers;
	}

	public Set<TRePlayPermission> getTRePlayPermissions() {
		return this.TRePlayPermissions;
	}

	public void setTRePlayPermissions(Set<TRePlayPermission> TRePlayPermissions) {
		this.TRePlayPermissions = TRePlayPermissions;
	}

	public Set<TReResourcePermission> getTReResourcePermissions() {
		return this.TReResourcePermissions;
	}

	public void setTReResourcePermissions(
			Set<TReResourcePermission> TReResourcePermissions) {
		this.TReResourcePermissions = TReResourcePermissions;
	}

	public Set<TReUsrgPermission> getTReUsrgPermissions() {
		return this.TReUsrgPermissions;
	}

	public void setTReUsrgPermissions(Set<TReUsrgPermission> TReUsrgPermissions) {
		this.TReUsrgPermissions = TReUsrgPermissions;
	}

	public Set<TReVedioSchedulePermission> getTReVedioSchedulePermissions() {
		return this.TReVedioSchedulePermissions;
	}

	public void setTReVedioSchedulePermissions(
			Set<TReVedioSchedulePermission> TReVedioSchedulePermissions) {
		this.TReVedioSchedulePermissions = TReVedioSchedulePermissions;
	}

	public Set<TReGroupPermission> getTReGroupPermissions() {
		return this.TReGroupPermissions;
	}

	public void setTReGroupPermissions(
			Set<TReGroupPermission> TReGroupPermissions) {
		this.TReGroupPermissions = TReGroupPermissions;
	}

}
