package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private String usrId;
	private TUserGroup TUserGroup;
	private String usrLogin;
	private String usrPassword;
	private String usrName;
	private Integer usrType;
	private String masterId;
	private String usrEmial;
	private String usrPhone;
	private String usrAddress;
	private Integer usrIsvalid;
	private Date usrCreateTime;
	private String usrBz;
	private Set<TReVedioSchedulePermission> TReVedioSchedulePermissions = new HashSet<TReVedioSchedulePermission>(
			0);
	private Set<TRePlayPermission> TRePlayPermissions = new HashSet<TRePlayPermission>(
			0);
	private Set<TReUsrgPermission> TReUsrgPermissions = new HashSet<TReUsrgPermission>(
			0);
	private Set<TReResourcePermission> TReResourcePermissions = new HashSet<TReResourcePermission>(
			0);
	private Set<TReGroupPermission> TReGroupPermissions = new HashSet<TReGroupPermission>(
			0);

	public TUser() {
	}

	public TUser(String usrId) {
		this.usrId = usrId;
	}

	public TUser(String usrId, TUserGroup TUserGroup, String usrLogin,
			String usrPassword, String usrName, Integer usrType,
			String masterId, String usrEmial, String usrPhone,
			String usrAddress, Integer usrIsvalid, Date usrCreateTime,
			String usrBz,
			Set<TReVedioSchedulePermission> TReVedioSchedulePermissions,
			Set<TRePlayPermission> TRePlayPermissions,
			Set<TReUsrgPermission> TReUsrgPermissions,
			Set<TReResourcePermission> TReResourcePermissions,
			Set<TReGroupPermission> TReGroupPermissions) {
		this.usrId = usrId;
		this.TUserGroup = TUserGroup;
		this.usrLogin = usrLogin;
		this.usrPassword = usrPassword;
		this.usrName = usrName;
		this.usrType = usrType;
		this.masterId = masterId;
		this.usrEmial = usrEmial;
		this.usrPhone = usrPhone;
		this.usrAddress = usrAddress;
		this.usrIsvalid = usrIsvalid;
		this.usrCreateTime = usrCreateTime;
		this.usrBz = usrBz;
		this.TReVedioSchedulePermissions = TReVedioSchedulePermissions;
		this.TRePlayPermissions = TRePlayPermissions;
		this.TReUsrgPermissions = TReUsrgPermissions;
		this.TReResourcePermissions = TReResourcePermissions;
		this.TReGroupPermissions = TReGroupPermissions;
	}

	public String getUsrId() {
		return this.usrId;
	}

	public void setUsrId(String usrId) {
		this.usrId = usrId;
	}

	public TUserGroup getTUserGroup() {
		return this.TUserGroup;
	}

	public void setTUserGroup(TUserGroup TUserGroup) {
		this.TUserGroup = TUserGroup;
	}

	public String getUsrLogin() {
		return this.usrLogin;
	}

	public void setUsrLogin(String usrLogin) {
		this.usrLogin = usrLogin;
	}

	public String getUsrPassword() {
		return this.usrPassword;
	}

	public void setUsrPassword(String usrPassword) {
		this.usrPassword = usrPassword;
	}

	public String getUsrName() {
		return this.usrName;
	}

	public void setUsrName(String usrName) {
		this.usrName = usrName;
	}

	public Integer getUsrType() {
		return this.usrType;
	}

	public void setUsrType(Integer usrType) {
		this.usrType = usrType;
	}

	public String getMasterId() {
		return this.masterId;
	}

	public void setMasterId(String masterId) {
		this.masterId = masterId;
	}

	public String getUsrEmial() {
		return this.usrEmial;
	}

	public void setUsrEmial(String usrEmial) {
		this.usrEmial = usrEmial;
	}

	public String getUsrPhone() {
		return this.usrPhone;
	}

	public void setUsrPhone(String usrPhone) {
		this.usrPhone = usrPhone;
	}

	public String getUsrAddress() {
		return this.usrAddress;
	}

	public void setUsrAddress(String usrAddress) {
		this.usrAddress = usrAddress;
	}

	public Integer getUsrIsvalid() {
		return this.usrIsvalid;
	}

	public void setUsrIsvalid(Integer usrIsvalid) {
		this.usrIsvalid = usrIsvalid;
	}

	public Date getUsrCreateTime() {
		return this.usrCreateTime;
	}

	public void setUsrCreateTime(Date usrCreateTime) {
		this.usrCreateTime = usrCreateTime;
	}

	public String getUsrBz() {
		return this.usrBz;
	}

	public void setUsrBz(String usrBz) {
		this.usrBz = usrBz;
	}

	public Set<TReVedioSchedulePermission> getTReVedioSchedulePermissions() {
		return this.TReVedioSchedulePermissions;
	}

	public void setTReVedioSchedulePermissions(
			Set<TReVedioSchedulePermission> TReVedioSchedulePermissions) {
		this.TReVedioSchedulePermissions = TReVedioSchedulePermissions;
	}

	public Set<TRePlayPermission> getTRePlayPermissions() {
		return this.TRePlayPermissions;
	}

	public void setTRePlayPermissions(Set<TRePlayPermission> TRePlayPermissions) {
		this.TRePlayPermissions = TRePlayPermissions;
	}

	public Set<TReUsrgPermission> getTReUsrgPermissions() {
		return this.TReUsrgPermissions;
	}

	public void setTReUsrgPermissions(Set<TReUsrgPermission> TReUsrgPermissions) {
		this.TReUsrgPermissions = TReUsrgPermissions;
	}

	public Set<TReResourcePermission> getTReResourcePermissions() {
		return this.TReResourcePermissions;
	}

	public void setTReResourcePermissions(
			Set<TReResourcePermission> TReResourcePermissions) {
		this.TReResourcePermissions = TReResourcePermissions;
	}

	public Set<TReGroupPermission> getTReGroupPermissions() {
		return this.TReGroupPermissions;
	}

	public void setTReGroupPermissions(
			Set<TReGroupPermission> TReGroupPermissions) {
		this.TReGroupPermissions = TReGroupPermissions;
	}

}
