package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

/**
 * TVersion generated by hbm2java
 */
public class TVersion implements java.io.Serializable {

	private Integer verId;
	private String verName;
	private Integer verSerial;

	public TVersion() {
	}

	public TVersion(String verName, Integer verSerial) {
		this.verName = verName;
		this.verSerial = verSerial;
	}

	public Integer getVerId() {
		return this.verId;
	}

	public void setVerId(Integer verId) {
		this.verId = verId;
	}

	public String getVerName() {
		return this.verName;
	}

	public void setVerName(String verName) {
		this.verName = verName;
	}

	public Integer getVerSerial() {
		return this.verSerial;
	}

	public void setVerSerial(Integer verSerial) {
		this.verSerial = verSerial;
	}

}
