package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TVideoSchedule generated by hbm2java
 */
public class TVideoSchedule implements java.io.Serializable {

	private String vsId;
	private TGroup TGroup;
	private String vsName;
	private Integer vsIndex;
	private String vsMode;
	private Set<TReVedioSchedulePermission> TReVedioSchedulePermissions = new HashSet<TReVedioSchedulePermission>(
			0);
	private Set<TVideoPlay> TVideoPlays = new HashSet<TVideoPlay>(0);

	public TVideoSchedule() {
	}

	public TVideoSchedule(String vsId) {
		this.vsId = vsId;
	}

	public TVideoSchedule(String vsId, TGroup TGroup, String vsName,
			Integer vsIndex, String vsMode,
			Set<TReVedioSchedulePermission> TReVedioSchedulePermissions,
			Set<TVideoPlay> TVideoPlays) {
		this.vsId = vsId;
		this.TGroup = TGroup;
		this.vsName = vsName;
		this.vsIndex = vsIndex;
		this.vsMode = vsMode;
		this.TReVedioSchedulePermissions = TReVedioSchedulePermissions;
		this.TVideoPlays = TVideoPlays;
	}

	public String getVsId() {
		return this.vsId;
	}

	public void setVsId(String vsId) {
		this.vsId = vsId;
	}

	public TGroup getTGroup() {
		return this.TGroup;
	}

	public void setTGroup(TGroup TGroup) {
		this.TGroup = TGroup;
	}

	public String getVsName() {
		return this.vsName;
	}

	public void setVsName(String vsName) {
		this.vsName = vsName;
	}

	public Integer getVsIndex() {
		return this.vsIndex;
	}

	public void setVsIndex(Integer vsIndex) {
		this.vsIndex = vsIndex;
	}

	public String getVsMode() {
		return this.vsMode;
	}

	public void setVsMode(String vsMode) {
		this.vsMode = vsMode;
	}

	public Set<TReVedioSchedulePermission> getTReVedioSchedulePermissions() {
		return this.TReVedioSchedulePermissions;
	}

	public void setTReVedioSchedulePermissions(
			Set<TReVedioSchedulePermission> TReVedioSchedulePermissions) {
		this.TReVedioSchedulePermissions = TReVedioSchedulePermissions;
	}

	public Set<TVideoPlay> getTVideoPlays() {
		return this.TVideoPlays;
	}

	public void setTVideoPlays(Set<TVideoPlay> TVideoPlays) {
		this.TVideoPlays = TVideoPlays;
	}

}
