package com.nvg.css.db.domain;

// Generated Jun 10, 2016 7:15:43 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TVideoPlay generated by hbm2java
 */
public class TVideoPlay implements java.io.Serializable {

	private String vpId;
	private TResource TResource;
	private TGroup TGroup;
	private TVideoSchedule TVideoSchedule;
	private String vpName;
	private Integer vpIndex;
	private Integer vpChannel;
	private String vpPlaySession;
	private String vpMulticastIp;
	private Integer vpMulticastPort;
	private Integer vpColumn;
	private Integer vpRow;
	private Integer vpTop;
	private Integer vpLeft;
	private Integer vpBottom;
	private Integer vpRight;
	private Integer vpHeight;
	private Integer vpWidth;
	private String vpDisplay;
	private String vpPosition;
	private String vpOverflow;
	private Integer vpLayer;
	private Integer vpPaddingTop;
	private Integer vpPaddingRight;
	private Integer vpPaddingBottom;
	private Integer vpPaddingLeft;
	private Set<TRePlayPermission> TRePlayPermissions = new HashSet<TRePlayPermission>(
			0);

	public TVideoPlay() {
	}

	public TVideoPlay(String vpId) {
		this.vpId = vpId;
	}

	public TVideoPlay(String vpId, TResource TResource, TGroup TGroup,
			TVideoSchedule TVideoSchedule, String vpName, Integer vpIndex,
			Integer vpChannel, String vpPlaySession, String vpMulticastIp,
			Integer vpMulticastPort, Integer vpColumn, Integer vpRow,
			Integer vpTop, Integer vpLeft, Integer vpBottom, Integer vpRight,
			Integer vpHeight, Integer vpWidth, String vpDisplay,
			String vpPosition, String vpOverflow, Integer vpLayer,
			Integer vpPaddingTop, Integer vpPaddingRight,
			Integer vpPaddingBottom, Integer vpPaddingLeft,
			Set<TRePlayPermission> TRePlayPermissions) {
		this.vpId = vpId;
		this.TResource = TResource;
		this.TGroup = TGroup;
		this.TVideoSchedule = TVideoSchedule;
		this.vpName = vpName;
		this.vpIndex = vpIndex;
		this.vpChannel = vpChannel;
		this.vpPlaySession = vpPlaySession;
		this.vpMulticastIp = vpMulticastIp;
		this.vpMulticastPort = vpMulticastPort;
		this.vpColumn = vpColumn;
		this.vpRow = vpRow;
		this.vpTop = vpTop;
		this.vpLeft = vpLeft;
		this.vpBottom = vpBottom;
		this.vpRight = vpRight;
		this.vpHeight = vpHeight;
		this.vpWidth = vpWidth;
		this.vpDisplay = vpDisplay;
		this.vpPosition = vpPosition;
		this.vpOverflow = vpOverflow;
		this.vpLayer = vpLayer;
		this.vpPaddingTop = vpPaddingTop;
		this.vpPaddingRight = vpPaddingRight;
		this.vpPaddingBottom = vpPaddingBottom;
		this.vpPaddingLeft = vpPaddingLeft;
		this.TRePlayPermissions = TRePlayPermissions;
	}

	public String getVpId() {
		return this.vpId;
	}

	public void setVpId(String vpId) {
		this.vpId = vpId;
	}

	public TResource getTResource() {
		return this.TResource;
	}

	public void setTResource(TResource TResource) {
		this.TResource = TResource;
	}

	public TGroup getTGroup() {
		return this.TGroup;
	}

	public void setTGroup(TGroup TGroup) {
		this.TGroup = TGroup;
	}

	public TVideoSchedule getTVideoSchedule() {
		return this.TVideoSchedule;
	}

	public void setTVideoSchedule(TVideoSchedule TVideoSchedule) {
		this.TVideoSchedule = TVideoSchedule;
	}

	public String getVpName() {
		return this.vpName;
	}

	public void setVpName(String vpName) {
		this.vpName = vpName;
	}

	public Integer getVpIndex() {
		return this.vpIndex;
	}

	public void setVpIndex(Integer vpIndex) {
		this.vpIndex = vpIndex;
	}

	public Integer getVpChannel() {
		return this.vpChannel;
	}

	public void setVpChannel(Integer vpChannel) {
		this.vpChannel = vpChannel;
	}

	public String getVpPlaySession() {
		return this.vpPlaySession;
	}

	public void setVpPlaySession(String vpPlaySession) {
		this.vpPlaySession = vpPlaySession;
	}

	public String getVpMulticastIp() {
		return this.vpMulticastIp;
	}

	public void setVpMulticastIp(String vpMulticastIp) {
		this.vpMulticastIp = vpMulticastIp;
	}

	public Integer getVpMulticastPort() {
		return this.vpMulticastPort;
	}

	public void setVpMulticastPort(Integer vpMulticastPort) {
		this.vpMulticastPort = vpMulticastPort;
	}

	public Integer getVpColumn() {
		return this.vpColumn;
	}

	public void setVpColumn(Integer vpColumn) {
		this.vpColumn = vpColumn;
	}

	public Integer getVpRow() {
		return this.vpRow;
	}

	public void setVpRow(Integer vpRow) {
		this.vpRow = vpRow;
	}

	public Integer getVpTop() {
		return this.vpTop;
	}

	public void setVpTop(Integer vpTop) {
		this.vpTop = vpTop;
	}

	public Integer getVpLeft() {
		return this.vpLeft;
	}

	public void setVpLeft(Integer vpLeft) {
		this.vpLeft = vpLeft;
	}

	public Integer getVpBottom() {
		return this.vpBottom;
	}

	public void setVpBottom(Integer vpBottom) {
		this.vpBottom = vpBottom;
	}

	public Integer getVpRight() {
		return this.vpRight;
	}

	public void setVpRight(Integer vpRight) {
		this.vpRight = vpRight;
	}

	public Integer getVpHeight() {
		return this.vpHeight;
	}

	public void setVpHeight(Integer vpHeight) {
		this.vpHeight = vpHeight;
	}

	public Integer getVpWidth() {
		return this.vpWidth;
	}

	public void setVpWidth(Integer vpWidth) {
		this.vpWidth = vpWidth;
	}

	public String getVpDisplay() {
		return this.vpDisplay;
	}

	public void setVpDisplay(String vpDisplay) {
		this.vpDisplay = vpDisplay;
	}

	public String getVpPosition() {
		return this.vpPosition;
	}

	public void setVpPosition(String vpPosition) {
		this.vpPosition = vpPosition;
	}

	public String getVpOverflow() {
		return this.vpOverflow;
	}

	public void setVpOverflow(String vpOverflow) {
		this.vpOverflow = vpOverflow;
	}

	public Integer getVpLayer() {
		return this.vpLayer;
	}

	public void setVpLayer(Integer vpLayer) {
		this.vpLayer = vpLayer;
	}

	public Integer getVpPaddingTop() {
		return this.vpPaddingTop;
	}

	public void setVpPaddingTop(Integer vpPaddingTop) {
		this.vpPaddingTop = vpPaddingTop;
	}

	public Integer getVpPaddingRight() {
		return this.vpPaddingRight;
	}

	public void setVpPaddingRight(Integer vpPaddingRight) {
		this.vpPaddingRight = vpPaddingRight;
	}

	public Integer getVpPaddingBottom() {
		return this.vpPaddingBottom;
	}

	public void setVpPaddingBottom(Integer vpPaddingBottom) {
		this.vpPaddingBottom = vpPaddingBottom;
	}

	public Integer getVpPaddingLeft() {
		return this.vpPaddingLeft;
	}

	public void setVpPaddingLeft(Integer vpPaddingLeft) {
		this.vpPaddingLeft = vpPaddingLeft;
	}

	public Set<TRePlayPermission> getTRePlayPermissions() {
		return this.TRePlayPermissions;
	}

	public void setTRePlayPermissions(Set<TRePlayPermission> TRePlayPermissions) {
		this.TRePlayPermissions = TRePlayPermissions;
	}

}
